# Chunk-grid scan at the benchmark strong cell with the register cache OFF (the NVIDIA default): Newton n=2 for
# EDM_SAMPLE_CHUNKS ∈ {1,2,3,4,5,6,8,12}; field-only, no cubes. CAMPAIGN=smoke is exempt from the drainer/teardown gate.
CAMPAIGN=smoke
SCRIPT=scripts/inverse_thomson_scattering.jl
KEEP_CUBE=0
BASE=(
  EDM_NX=401 EDM_FIELD_MODE=total EDM_NSUBSTEPS=1 EDM_RELTOL=1e-13 EDM_A0=0.3 EDM_INTERP_SAVEAT=16
  EDM_INITIAL_PHASE=-1.5707963267948966 EDM_WINDOW=narrow EDM_APODIZATION=none EDM_DIRECT_READ=1
  EDM_GAMMA_EPS=4 EDM_SPP=512 EDM_TSPAN_TAU=3.2 EDM_SCREEN_HW=3.0 EDM_HARMONICS=97.1395,98,193.6813,196
  EDM_SWEEP=chunks_scan_nocache EDM_N=32 EDM_SKIP_POSTPROCESS=1 EDM_GPU_SAMPLE_DT=0.5 EDM_ACCUM_ALG=newton EDM_NEWTON_ITERS=2 EDM_COEF_REUSE=0
)
CELLS=(
  "nc_c1|EDM_SAMPLE_CHUNKS=1"
  "nc_c2|EDM_SAMPLE_CHUNKS=2"
  "nc_c3|EDM_SAMPLE_CHUNKS=3"
  "nc_c4|EDM_SAMPLE_CHUNKS=4"
  "nc_c5|EDM_SAMPLE_CHUNKS=5"
  "nc_c6|EDM_SAMPLE_CHUNKS=6"
  "nc_c8|EDM_SAMPLE_CHUNKS=8"
  "nc_c12|EDM_SAMPLE_CHUNKS=12"
)
